### ISSUE TITLE
Problem in layout

### ISSUE THREAD

**Issue by Djabx** [cozy/cozy-docs-v3#30]
Hi,

In the cozy documentation I've a problem of layout (from top to bottom firefox, edge chrome) on windows.

![doc_cozy](https://user-images.githubusercontent.com/69534/35391018-a36838b6-01dd-11e8-8dd2-f9504ca7cd35.PNG)

**Comment by CPatchane** [comment]
Hey, thanks for opening this issue @Djabx. It should be fixed by the PR #31 👍

**Comment by ptbrowne** [comment]
Fixed in #31
