### ISSUE TITLE
Adding References as first level menu breaks the layout

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-docs-v3#45]
![firefox_screenshot_2018-03-30t08-14-15 086z](https://user-images.githubusercontent.com/384908/38130443-6b9a600a-3403-11e8-9982-58c416bb80da.png)

Maybe « References » could be a sub-menu of « Develop ».

**Comment by ptbrowne** [comment]
Ah yes, I had not seen on my screens. I'll put the References under Develop 👍

**Comment by ptbrowne** [comment]
Fixed in https://github.com/cozy/cozy-docs-v3/commit/080e99c7899a6ab3717822704542592e285d04e0
